version: "3.8"
services:
  iis-server:
    image: erewhon/iis-server:v1
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${IISLogPath:-c:\Erewhon\iis_logs}:c:\inetpub\logs\FailedReqLogFiles\W3SVC1
      - ${IISLogPath:-c:\Erewhon\iis_logs}:c:\bin_jadehttp\logs
    ports:
      - "6109:80"  

networks:
  default:
    external: true  
    name: nat
