version: "3.8"
services:
  jade-rap:
    image: ${Registry:-}/jade/database-server:${Tag:-20.0.02-x64-U}
    volumes:
      - ${DatabasePath:-c:\Erewhon\system}:c:\jade\system
      - ${JournalPath:-c:\Erewhon\journals}:c:\jade\journals
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
      - ${DumpsPath:-c:\Erewhon\ProcessDumps}:c:\jade\ProcessDumps
    ports:
      - "${RapListenPort:-9901}:9901"

  jade-app-server:
    image: ${Registry:-}/${RepoPrefix:-}/application-server:${Tag:-20.0.02-x64-U}
    container_name: "jade-app-server"
    depends_on: 
      - jade-rap
    volumes:
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    ports:
      - "${AppServerListenPort:-443}:9907"

  erewhon-webshop:
    depends_on: 
      - jade-rap
      - iis-server
    image: erewhon/webshop:v2
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    expose:
      - "6107"

  erewhon-rest:
    depends_on: 
      - jade-rap
      - iis-server
    image: erewhon/rest-api:v2
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    expose:
      - "6108"
  
  iis-server:
    image: erewhon/iis-server:v2
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${IISLogPath:-c:\Erewhon\iis_logs\FailedReqLogFiles}:C:\inetpub\logs\FailedReqLogFiles\W3SVC1
      - ${IISLogPath:-c:\Erewhon\iis_logs}:C:\bin_jadehttp\logs
    ports:
      - "6109:6109"  

networks:
  default:
    external: true  
    name: nat

      