version: "3.8"
services:
  erewhon-webshop:
    image: erewhon/webshop:v1
    volumes:
      - ${ImagesPath:-c:\jade\images}:c:\temp
      - ${LogPath:-c:\jade\logs}:c:\logs
    expose:
      - "6107"
    networks:
      - jade-net

networks:
  jade-net:
    external:
      name: nat
