version: "3.8"
services:
  erewhon-webshop:
    image: erewhon/webshop:v1
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    expose:
      - "6107"

networks:
  default:
    external: true  
    name: nat
