version: "3.8"
services:
  jade-erewhon-rest:
    image: erewhon/rest-api:v1
    container_name: "jade-erewhon-rest"
    volumes:
      - ${ImagesPath:-c:\jade\images}:c:\temp
      - ${LogPath:-c:\jade\logs}:c:\logs
    ports:
      - "6108:6108"
    networks:
      - jade-net
      
networks:
  jade-net:
    external:
      name: nat
