version: "3.8"
services:
  erewhon-rest:
    image: erewhon/rest-api:v1
    volumes:
      - ${ImagesPath:-c:\Erewhon\images}:c:\temp
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    expose:
      - "6108"
      
networks:
  default:
    external: true  
    name: nat
