version: "3.8"
services:
  erewhon-rest:
    image: erewhon/rest-api:v1
    volumes:
      - ${ImagesPath:-c:\jade\images}:c:\temp
      - ${LogPath:-c:\jade\logs}:c:\logs
    expose:
      - "6108"
    networks:
      - jade-net
      
networks:
  jade-net:
    external:
      name: nat
