version: "3.8"
services:

  jade-rap:
    image: ${Registry:-}/${RepoPrefix:-}/database-server:${Tag:-22.0.02-x64-U}
    volumes:
      - ${DatabasePath:-c:\Erewhon\system}:c:\jade\system
      - ${JournalPath:-c:\Erewhon\journals}:c:\jade\journals
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    ports:
      - "${RapListenPort:-9901}:9901"

  jade-app-server:
    image: ${Registry:-}/${RepoPrefix:-}/application-server:${Tag:-22.0.02-x64-U}
    depends_on: 
      - jade-rap
    volumes:
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs
    ports:
      - "${AppServerListenPort:-443}:9907"

  jade-client:
    image: ${Registry:-}/${RepoPrefix:-}/non-gui-client:${Tag:-22.0.02-x64-U}
    depends_on: 
      - jade-rap
    volumes:
      - ${LogPath:-c:\Erewhon\logs}:c:\jade\logs

networks:
  default:
    external: true  
    name: nat
    