version: "3.4"
services:

  rap:
    image: jade-database-server:99.0.00-x64-A
    volumes:
      - c:\jade\system:C:\system
      - c:\jade\journals:C:\journals
      - c:\jade\logs:C:\logs
    ports:
      - "9901:9901"
    networks:
      - jade-net
    build:
      context: ../components/jade-database-server
      dockerfile: ./Dockerfile

  app_server:
    image: jade-app-server:99.0.00-x64-A
    depends_on: 
      - rap
    volumes:
      - c:\jade\logs:C:\logs
    ports:
      - "443:9907"
    networks:
      - jade-net
    build:
      context: ../jade-app-server
      dockerfile: ./Dockerfile

networks:
  jade-net:
    external:
      name: nat
